translate_mappings = {
    #"name": "name",
    #"displayName": "displayName",
    #"tier": "tier",
    #"set": "set",
    "sockets": "slots",
    #"type": "type",
    #"armorType": "armorType", (deleted)
    "armorColor": "color", #(deleted)
    "addedLore": "lore", #(deleted)
    #"material": "material", (deleted)
    "dropType": "drop",
    #"quest": "quest",
    "restrictions": "restrict",
    "damage": "nDam",
    "fireDamage": "fDam",
    "waterDamage": "wDam",
    "airDamage": "aDam",
    "thunderDamage": "tDam",
    "earthDamage": "eDam",
    "attackSpeed": "atkSpd",
    "health": "hp",
    "fireDefense": "fDef",
    "waterDefense": "wDef",
    "airDefense": "aDef",
    "thunderDefense": "tDef",
    "earthDefense": "eDef",
    "level": "lvl",
    "classRequirement": "classReq",
    "strength": "strReq",
    "dexterity": "dexReq",
    "intelligence": "intReq",
    "agility": "agiReq",
    "defense": "defReq",
    "healthRegen": "hprPct",
    "manaRegen": "mr",
    #"spellDamage": "sdPct",
    "spellDamageBonus": "sdPct",
    "spellFireDamageBonus": "fSdPct",
    "spellWaterDamageBonus": "wSdPct",
    "spellAirDamageBonus": "aSdPct",
    "spellThunderDamageBonus": "tSdPct",
    "spellEarthDamageBonus": "eSdPct",
    #"damageBonus": "mdPct",
    "mainAttackDamageBonus": "mdPct",
    "mainAttackFireDamageBonus": "fMdPct",
    "mainAttackWaterDamageBonus": "wMdPct",
    "mainAttackAirDamageBonus": "aMdPct",
    "mainAttackThunderDamageBonus": "tMdPct",
    "mainAttackEarthDamageBonus": "eMdPct",
    "lifeSteal": "ls",
    "manaSteal": "ms",
    "xpBonus": "xpb",
    "lootBonus": "lb",
    "reflection": "ref",
    "strengthPoints": "str",
    "dexterityPoints": "dex",
    "intelligencePoints": "int",
    "agilityPoints": "agi",
    "defensePoints": "def",
    #"thorns": "thorns",
    "exploding": "expd",
    "speed": "spd",
    "attackSpeedBonus": "atkTier",
    #"poison": "poison",
    "healthBonus": "hpBonus",
    "soulPoints": "spRegen",
    "emeraldStealing": "eSteal",
    "healthRegenRaw": "hprRaw",
    #"spellDamageRaw": "sdRaw",
    "spellDamageBonusRaw": "sdRaw",
    "spellFireDamageBonusRaw": "fSdRaw",
    "spellWaterDamageBonusRaw": "wSdRaw",
    "spellAirDamageBonusRaw": "aSdRaw",
    "spellThunderDamageBonusRaw": "tSdRaw",
    "spellEarthDamageBonusRaw": "eSdRaw",
    #"damageBonusRaw": "mdRaw",
    "mainAttackDamageBonusRaw": "mdRaw",
    "mainAttackFireDamageBonusRaw": "fMdRaw",
    "mainAttackWaterDamageBonusRaw": "wMdRaw",
    "mainAttackAirDamageBonusRaw": "aMdRaw",
    "mainAttackThunderDamageBonusRaw": "tMdRaw",
    "mainAttackEarthDamageBonusRaw": "eMdRaw",
    #"bonusFireDamage": "fDamPct",
    #"bonusWaterDamage": "wDamPct",
    #"bonusAirDamage": "aDamPct",
    #"bonusThunderDamage": "tDamPct",
    #"bonusEarthDamage": "eDamPct",
    "fireDamageBonus": "fDamPct",
    "waterDamageBonus": "wDamPct",
    "airDamageBonus": "aDamPct",
    "thunderDamageBonus": "tDamPct",
    "earthDamageBonus": "eDamPct",
    "bonusFireDefense": "fDefPct",
    "bonusWaterDefense": "wDefPct",
    "bonusAirDefense": "aDefPct",
    "bonusThunderDefense": "tDefPct",
    "bonusEarthDefense": "eDefPct",
    "accessoryType": "type",
    "identified": "fixID",
    #"skin": "skin",
    #"category": "category",

    "spellCostPct1": "spPct1",
    "spellCostRaw1": "spRaw1",
    "spellCostPct2": "spPct2",
    "spellCostRaw2": "spRaw2",
    "spellCostPct3": "spPct3",
    "spellCostRaw3": "spRaw3",
    "spellCostPct4": "spPct4",
    "spellCostRaw4": "spRaw4",

    #"rainbowSpellDamageRaw": "rainbowRaw",
    "spellElementalDamageBonusRaw": "rSdRaw",
    #"sprint": "sprint",
    "sprintRegen": "sprintReg",
    "jumpHeight": "jh",
    "lootQuality": "lq",

    "gatherXpBonus": "gXp",
    "gatherSpeed": "gSpd",
}

delete_keys = [
    #"addedLore",
    #"skin",
    #"armorType",
    #"armorColor",
    #"material"
]
